/*
 * Copyright (c) 2014, Fuzhou Rockchip Electronics Co., Ltd
 * Author: addy ke <addy.ke@rock-chips.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/clk.h>
#include <linux/mmc/host.h>
#include <linux/mmc/dw_mmc.h>
#include <linux/of_address.h>
#include <linux/mmc/host.h>
#include <linux/regmap.h>
#include <linux/mfd/syscon.h>

#include "dw_mmc.h"
#include "dw_mmc-pltfm.h"

#define RK3288_CLKGEN_DIV       2

#define GRF_IO_VSEL		0x380

#define IO_DOMAIN_VOLTAGE_330	0
#define IO_DOMAIN_VOLTAGE_180	1

/* bit[2]: flash0/emmc voltage selection bit
 * bit[7]: sdcard voltage selection bit
 * bit[4]: wifi/sdio0 voltage selection bit
 * bit[3]: flash1/sdio1 voltage selection bit
 */
static u32 io_vsel_bt[4] = {2, 7, 4, 3};

struct dw_mci_rk3288_priv_data {
	int ctrl_id;
	struct regmap *cru;
	struct regmap *grf;
};

static void dw_mci_rk3288_set_io_domain_voltage(struct dw_mci *host,
						int voltage)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	u32 bit = io_vsel_bt[priv->ctrl_id];
	u32 val = (voltage << bit) | (1 << (bit + 16));

	regmap_write(priv->grf, GRF_IO_VSEL, val);
}

static int dw_mci_rk3288_parse_dt(struct dw_mci *host)
{
	struct dw_mci_rk3288_priv_data *priv;
	struct device_node *np = host->dev->of_node;
	int default_voltage;

	priv = devm_kzalloc(host->dev, sizeof(*priv), GFP_KERNEL);
	if (!priv) {
		dev_err(host->dev, "mem alloc failed for private data\n");
		return -ENOMEM;
	}

	priv->ctrl_id = of_alias_get_id(np, "mshc");
	if(priv->ctrl_id < 0) {
		dev_err(host->dev, "dwmmc needs 'mshc' property\n");
		return -EINVAL;
	}

	priv->cru = syscon_regmap_lookup_by_phandle(np, "rockchip,cru");
	if (IS_ERR(priv->cru)) {
		dev_err(host->dev, "dwmmc needs 'rockchip,cru' property\n");
		return PTR_ERR(priv->cru);
	}

	priv->grf = syscon_regmap_lookup_by_phandle(np, "rockchip,grf");
	if (IS_ERR(priv->grf)) {
		dev_err(host->dev, "dwmmc needs 'rockchip,grf' property\n");
		return PTR_ERR(priv->grf);
	}

	host->priv = priv;

	if (!of_property_read_u32(np, "default_voltage", &default_voltage))
		dw_mci_rk3288_set_io_domain_voltage(host, default_voltage);

	return 0;
}

static void dw_mci_rockchip_prepare_command(struct dw_mci *host, u32 *cmdr)
{
	*cmdr |= SDMMC_CMD_USE_HOLD_REG;
}

static int dw_mci_rk3288_setup_clock(struct dw_mci *host)
{
	host->bus_hz /= RK3288_CLKGEN_DIV;

	return 0;
}

static void dw_mci_rk3288_set_ios(struct dw_mci *host, struct mmc_ios *ios)
{
	int ret;
	unsigned int cclkin;
	u32 bus_hz;

	/*
	 * cclkin: source clock of mmc controller
	 * bus_hz: card interface clock generated by CLKGEN
	 * bus_hz = cclkin / RK3288_CLKGEN_DIV
	 * os->clock = (div == 0) ? bus_hz : (bus_hz / (2 * div))
	 *
	 * Note: div can only be 0 or 1
	 *       if DDR50 8bit mode(only emmc work in 8bit mode),
	 *       div must be set 1
	 */
	if (ios->bus_width == MMC_BUS_WIDTH_8 &&
	    ios->timing == MMC_TIMING_MMC_DDR52)
		cclkin = 2 * ios->clock * RK3288_CLKGEN_DIV;
	else
		cclkin = ios->clock * RK3288_CLKGEN_DIV;

	ret = clk_set_rate(host->ciu_clk, cclkin);
	if (ret)
		dev_warn(host->dev, "failed to set rate %uHz\n", ios->clock);

	bus_hz = clk_get_rate(host->ciu_clk) / RK3288_CLKGEN_DIV;
	if (bus_hz != host->bus_hz) {
		host->bus_hz = bus_hz;
		/* force dw_mci_setup_bus() */
		host->current_speed = 0;
	}
}

static unsigned long rockchip_dwmmc_caps[] = {
	MMC_CAP_CMD23,
	MMC_CAP_CMD23,
	MMC_CAP_CMD23,
	MMC_CAP_CMD23,
};

static const struct dw_mci_drv_data rk2928_drv_data = {
	.caps			= rockchip_dwmmc_caps,
	.prepare_command        = dw_mci_rockchip_prepare_command,
};

static const struct dw_mci_drv_data rk3288_drv_data = {
	.caps			= rockchip_dwmmc_caps,
	.parse_dt		= dw_mci_rk3288_parse_dt,
	.prepare_command        = dw_mci_rockchip_prepare_command,
	.set_ios		= dw_mci_rk3288_set_ios,
	.setup_clock		= dw_mci_rk3288_setup_clock,
};

static const struct of_device_id dw_mci_rockchip_match[] = {
	{ .compatible = "rockchip,rk2928-dw-mshc",
		.data = &rk2928_drv_data },
	{ .compatible = "rockchip,rk3288-dw-mshc",
		.data = &rk3288_drv_data },
	{},
};
MODULE_DEVICE_TABLE(of, dw_mci_rockchip_match);

static int dw_mci_rockchip_probe(struct platform_device *pdev)
{
	const struct dw_mci_drv_data *drv_data;
	const struct of_device_id *match;

	match = of_match_node(dw_mci_rockchip_match, pdev->dev.of_node);
	drv_data = match->data;

	return dw_mci_pltfm_register(pdev, drv_data);
}

#ifdef CONFIG_PM_SLEEP
static int dw_mci_rockchip_suspend(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);
	int ret;

	ret = dw_mci_suspend(host);
	if (!ret)
		clk_disable_unprepare(host->ciu_clk);

	return ret;
}

static int dw_mci_rockchip_resume(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);
	int ret;

	ret = clk_prepare_enable(host->ciu_clk);
	if (ret) {
		dev_err(host->dev, "failed to enable ciu clock\n");
		return ret;
	}

	return dw_mci_resume(host);
}
#endif /* CONFIG_PM_SLEEP */

static SIMPLE_DEV_PM_OPS(dw_mci_rockchip_pmops,
			 dw_mci_rockchip_suspend,
			 dw_mci_rockchip_resume);

static struct platform_driver dw_mci_rockchip_pltfm_driver = {
	.probe		= dw_mci_rockchip_probe,
	.remove		= dw_mci_pltfm_remove,
	.driver		= {
		.name		= "dwmmc_rockchip",
		.of_match_table	= dw_mci_rockchip_match,
		.pm		= &dw_mci_rockchip_pmops,
	},
};

module_platform_driver(dw_mci_rockchip_pltfm_driver);

MODULE_AUTHOR("Addy Ke <addy.ke@rock-chips.com>");
MODULE_DESCRIPTION("Rockchip Specific DW-MSHC Driver Extension");
MODULE_ALIAS("platform:dwmmc-rockchip");
MODULE_LICENSE("GPL v2");
