/*
 * Copyright (c) 2014, Fuzhou Rockchip Electronics Co., Ltd
 * Author: addy ke <addy.ke@rock-chips.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/clk.h>
#include <linux/mmc/host.h>
#include <linux/mmc/dw_mmc.h>
#include <linux/of_address.h>
#include <linux/mmc/host.h>
#include <linux/regmap.h>
#include <linux/mfd/syscon.h>
#include <linux/mmc/mmc.h>
#include <linux/slab.h>
#include <linux/delay.h>
#include <linux/pinctrl/consumer.h>

#include "dw_mmc.h"
#include "dw_mmc-pltfm.h"

#define RK3288_CLKGEN_DIV	2

#define GRF_IO_VSEL		0x380

#define IO_DOMAIN_VOLTAGE_330	0
#define IO_DOMAIN_VOLTAGE_180	1

/* bit[7]: sdcard voltage selection bit
 * bit[4]: wifi/sdio0 voltage selection bit
 * bit[3]: flash1/sdio1 voltage selection bit
 * bit[2]: flash0/emmc voltage selection bit
 */
static u32 io_vsel_bt[4] = {7, 4, 3, 2};

enum tuning_type {
	TUNING_DRIVE = 0,
	TUNING_SAMPLE,
};

#define CRU_TUNING_REG(id, type)	(0x200 + 4 * ((id) * 2 + (type)))

#define TUNING_TYPE_OFF(type)		(((type) == TUNING_SAMPLE) ? 10 : 11)
#define TUNING_TYPE_MASK		0x01

#define TUNING_DEGREE_OFF(type)		(((type) == TUNING_SAMPLE) ? 0 : 1)
#define TUNING_DEGREE_MASK		0x03

#define TUNING_DELAYNUM_OFF(type)	(((type) == TUNING_SAMPLE) ? 2 : 3)
#define TUNING_DELAYNUM_MASK		0xff

#define MIN_STEP			2
#define MAX_STEP			((TUNING_DELAYNUM_MASK + 1) / 8)

struct dw_mci_rk3288_priv_data {
	int ctrl_id;
	enum tuning_type type;
	struct regmap *cru;
	struct regmap *grf;
	struct pinctrl *pinctrl;
	struct pinctrl_state *pins_power_on;
	struct pinctrl_state *pins_power_off;
};

static void dw_mci_rk3288_set_io_domain_voltage(struct dw_mci *host,
						int voltage)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	u32 bit = io_vsel_bt[priv->ctrl_id];
	u32 val = (voltage << bit) | (1 << (bit + 16));

	regmap_write(priv->grf, GRF_IO_VSEL, val);
}

static int dw_mci_rk3288_parse_dt(struct dw_mci *host)
{
	struct dw_mci_rk3288_priv_data *priv;
	struct device_node *np = host->dev->of_node;
	int default_voltage = 0;

	priv = devm_kzalloc(host->dev, sizeof(*priv), GFP_KERNEL);
	if (!priv) {
		dev_err(host->dev, "mem alloc failed for private data\n");
		return -ENOMEM;
	}

	priv->ctrl_id = of_alias_get_id(np, "mshc");
	if(priv->ctrl_id < 0) {
		dev_err(host->dev, "dwmmc needs 'mshc' property\n");
		return -EINVAL;
	}

	priv->cru = syscon_regmap_lookup_by_phandle(np, "rockchip,cru");
	if (IS_ERR(priv->cru)) {
		dev_err(host->dev, "dwmmc needs 'rockchip,cru' property\n");
		return PTR_ERR(priv->cru);
	}

	priv->grf = syscon_regmap_lookup_by_phandle(np, "rockchip,grf");
	if (IS_ERR(priv->grf)) {
		dev_err(host->dev, "dwmmc needs 'rockchip,grf' property\n");
		return PTR_ERR(priv->grf);
	}

	if(of_property_read_u32(np, "tuning_type", &priv->type)) {
		dev_err(host->dev, "dwmmc needs 'tuning_type' property\n");
		return -EINVAL;
	}

	priv->pinctrl = devm_pinctrl_get(host->dev);
	if (IS_ERR(priv->pinctrl)) {
		dev_err(host->dev, "failed to get pinctrl\n");
		return PTR_ERR(priv->pinctrl);	
	}

	priv->pins_power_on = pinctrl_lookup_state(
				priv->pinctrl,
				"power_on");

	priv->pins_power_off = pinctrl_lookup_state(
				priv->pinctrl,
				"power_off");

	host->priv = priv;

	if (!of_property_read_u32(np, "default_voltage", &default_voltage))
		dw_mci_rk3288_set_io_domain_voltage(host, default_voltage);

	dev_dbg(host->dev, "ctrl_id %d, tuninig_type %d, default_voltage %d\n",
				priv->ctrl_id, priv->type, default_voltage);

	return 0;
}

static void dw_mci_rockchip_prepare_command(struct dw_mci *host, u32 *cmdr)
{
	*cmdr |= SDMMC_CMD_USE_HOLD_REG;
}

static int dw_mci_rk3288_setup_clock(struct dw_mci *host)
{
	host->bus_hz /= RK3288_CLKGEN_DIV;

	return 0;
}

static void dw_mci_rk3288_set_ios(struct dw_mci *host, struct mmc_ios *ios)
{
	int ret;
	unsigned int cclkin;
	u32 bus_hz;
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	struct pinctrl_state *s = NULL;

	if (!IS_ERR(priv->pins_power_on) && !IS_ERR(priv->pins_power_on)) {
		switch (ios->power_mode) {
		case MMC_POWER_UP:
		case MMC_POWER_ON:
			s = priv->pins_power_on;
			if (ios->signal_voltage == MMC_SIGNAL_VOLTAGE_180)
				dw_mci_rk3288_set_io_domain_voltage(host, 1);
			else
				dw_mci_rk3288_set_io_domain_voltage(host, 0);
				
			break;
		case MMC_POWER_OFF:
			s = priv->pins_power_off;
			break;
		default:
			s = priv->pins_power_off;
			break;
		}
		pinctrl_select_state(priv->pinctrl, s);
	}
	/*
	 * cclkin: source clock of mmc controller
	 * bus_hz: card interface clock generated by CLKGEN
	 * bus_hz = cclkin / RK3288_CLKGEN_DIV
	 * os->clock = (div == 0) ? bus_hz : (bus_hz / (2 * div))
	 *
	 * Note: div can only be 0 or 1
	 *       if DDR50 8bit mode(only emmc work in 8bit mode),
	 *       div must be set 1
	 */
	if (ios->bus_width == MMC_BUS_WIDTH_8 &&
	    ios->timing == MMC_TIMING_MMC_DDR52)
		cclkin = 2 * ios->clock * RK3288_CLKGEN_DIV;
	else
		cclkin = ios->clock * RK3288_CLKGEN_DIV;

	ret = clk_set_rate(host->ciu_clk, cclkin);
	if (ret)
		dev_warn(host->dev, "failed to set rate %uHz\n", ios->clock);

	bus_hz = clk_get_rate(host->ciu_clk) / RK3288_CLKGEN_DIV;
	if (bus_hz != host->bus_hz) {
		host->bus_hz = bus_hz;
		/* force dw_mci_setup_bus() */
		host->current_speed = 0;
	}
}

static u8 dw_mci_rk3288_tuning_test(struct dw_mci_slot *slot, u32 opcode,
				    struct dw_mci_tuning_data *tuning_data)
{
	struct dw_mci *host = slot->host;
	struct mmc_host *mmc = slot->mmc;
	const u8 *blk_pattern = tuning_data->blk_pattern;
	u8 *blk_test;
	unsigned int blksz = tuning_data->blksz;
	u8 ret = 0;

	struct mmc_request mrq = {NULL};
	struct mmc_command cmd = {0};
	struct mmc_command stop = {0};
	struct mmc_data data = {0};
	struct scatterlist sg;

	blk_test = kzalloc(blksz, GFP_KERNEL);
	if (!blk_test)
		return -ENOMEM;
	
	cmd.opcode = opcode;
	cmd.arg = 0;
	cmd.flags = MMC_RSP_R1 | MMC_CMD_ADTC;
	stop.opcode = MMC_STOP_TRANSMISSION;
	stop.arg = 0;
	stop.flags = MMC_RSP_R1B | MMC_CMD_AC;

	data.blksz = blksz;
	data.blocks = 1;
	data.flags = MMC_DATA_READ;
	data.sg = &sg;
	data.sg_len = 1;

	sg_init_one(&sg, blk_test, blksz);
	mrq.cmd = &cmd;
	mrq.stop = &stop;
	mrq.data = &data;
	host->mrq = &mrq;

	mci_writel(host, TMOUT, ~0);

	mmc_wait_for_req(mmc, &mrq);
	if (!cmd.error && !data.error) {
		if (!memcmp(blk_pattern, blk_test, blksz))
			ret = 1;
	} else {
		dev_dbg(host->dev,
			"Tuning error: cmd.error:%d, data.error:%d\n",
			cmd.error, data.error);
	}

	kfree(blk_test);

	return ret;
}

static void dw_mci_rk3288_set_degree(struct dw_mci *host, int degree)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	unsigned int reg;
	unsigned int val;
	unsigned int off;

	reg = CRU_TUNING_REG(priv->ctrl_id, priv->type);
	off = TUNING_DEGREE_OFF(priv->type);
	val = (degree << off) | (TUNING_DEGREE_MASK << (off + 16));

	regmap_write(priv->cru, reg, val);
}

static void dw_mci_rk3288_set_delaynum(struct dw_mci *host, int delaynum)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	unsigned int reg;
	unsigned int val;
	unsigned int off;

	reg = CRU_TUNING_REG(priv->ctrl_id, priv->type);
	off = TUNING_DELAYNUM_OFF(priv->type);
	val = (delaynum << off) | (TUNING_DELAYNUM_MASK << (off + 16));

	regmap_write(priv->cru, reg, val);
}

static void dw_mci_rk3288_tuning_drive_on(struct dw_mci *host, int on)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	unsigned int reg;
	unsigned int val;
	unsigned int off;

	reg = CRU_TUNING_REG(priv->ctrl_id, TUNING_DRIVE);
	off = TUNING_TYPE_OFF(TUNING_DRIVE);
	val = (on << off) | (TUNING_TYPE_MASK << (off + 16));

	regmap_write(priv->cru, reg, val);
}

static void dw_mci_rk3288_tuning_sample_on(struct dw_mci *host, int on)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	unsigned int reg;
	unsigned int val;
	unsigned int off;

	reg = CRU_TUNING_REG(priv->ctrl_id, TUNING_SAMPLE);
	off = TUNING_TYPE_OFF(TUNING_SAMPLE);
	val = (on << off) | (TUNING_TYPE_MASK << (off + 16));

	regmap_write(priv->cru, reg, val);
}

static void dw_mci_rk3288_set_tuning_type(struct dw_mci *host)
{
	struct dw_mci_rk3288_priv_data *priv = host->priv;
	
	if (priv->type == TUNING_SAMPLE) {
		dw_mci_rk3288_tuning_sample_on(host, 1);
		dw_mci_rk3288_tuning_drive_on(host, 0);
	} else {
		dw_mci_rk3288_tuning_sample_on(host, 0);
		dw_mci_rk3288_tuning_drive_on(host, 1);
	}
}

static u8 dw_mci_rk3288_get_degree_candiates(
		struct dw_mci_slot *slot, u32 opcode,
		struct dw_mci_tuning_data *tuning_data)
{
	struct dw_mci *host = slot->host;
	const u8 iter = TUNING_DEGREE_MASK + 1;
	u8 i;
	u8 candiates = 0;
	u8 ret;

	for (i = 0; i < iter; i++) {
		dw_mci_rk3288_set_degree(host, i);
		ret = dw_mci_rk3288_tuning_test(slot, opcode, tuning_data);
		candiates |= (ret << i);
	}

	return candiates;
}

static int dw_mci_rk3288_get_best_degree(
		struct dw_mci_slot *slot, u32 opcode,
		struct dw_mci_tuning_data *tuning_data,
		bool *need_adjust_delaynum)
{
	u8 candiates = 0;
	const u8 iter = TUNING_DEGREE_MASK + 1;
	u8 __c;
	int i;

	candiates =
		dw_mci_rk3288_get_degree_candiates(slot, opcode, tuning_data);
	
	/* If there are three consecutive degrees which pass the test,
	 * then we take the middle degree and do not adjust delaynum.
	 */
	for (i = 0; i < iter; i++) {
		__c = ror8(candiates, i);
		if ((__c & 0x83) == 0x83) {
			*need_adjust_delaynum = false;
			return i;
		}
	}

	/* If there are two consecutive degrees which pass the test,
	 * then we take the low degree and must adjust delaynum.
	 */
	for (i = 0; i < iter; i++) {
		__c = ror8(candiates, i);
		if ((__c & 0x03) == 0x03) {
			*need_adjust_delaynum = true;
			return i;
		}
	}

	/* If there is only one degree which pass the test,
	 * then we take the degree before it and must adjust delaynum.
	 */
	for (i = 0; i < iter; i++) {
		__c = ror8(candiates, i);
		if ((__c & 0x01) == 0x01) {
			*need_adjust_delaynum = true;
			return i - 1;
		}
	}

	return -1;
}

static int dw_mci_rk3288_get_start_delaynum(u8 candiates, u8 step)
{
	const u8 iter = 8;
	u8 __c;
	int i;
	int num = 0;

	/* take the first delaynum which pass the test */
	for (i = 0; i < iter; i++) {
		__c = ror8(candiates, i);
		if ((__c & 0x01) == 0x01) {
			num = (i == 0) ? 0 : (i - 1);
			break;
		}
	}

	return num * step;
}

static u8 dw_mci_rk3288_get_delaynum_candiates(
		struct dw_mci_slot *slot, u32 opcode,
		struct dw_mci_tuning_data *tuning_data,
		u8 old_candiates,
		int start_delaynum,
		u8 step)
{
	struct dw_mci *host = slot->host;
	const u8 iter = 8;
	int i;
	u8 candiates = 0;
	u8 ret;

	for (i = 0; i < iter; i++) {
		dw_mci_rk3288_set_delaynum(host, i * step + start_delaynum);
		ret = dw_mci_rk3288_tuning_test(slot, opcode, tuning_data);
		candiates |= (ret << i);
	}

	return candiates;
}

static int dw_mci_rk3288_get_best_delaynum(
		struct dw_mci_slot *slot,
		u32 opcode,
		struct dw_mci_tuning_data *tuning_data)
{
	u8 step = MAX_STEP;
	u8 candiates = 0;
	int start_delaynum = 0;
	const u8 iter = 8;
	u8 __c;
	int i;

	do {
		start_delaynum =
			dw_mci_rk3288_get_start_delaynum(candiates, step);
		candiates = dw_mci_rk3288_get_delaynum_candiates(
			slot, opcode, tuning_data,
			candiates, start_delaynum, step);

		/* If there are three or more consecutive delaynums
		 * which pass the test, then we take the middle delaynum.
		 */
		if (candiates == 0xff)
			return 3;
		for (i = 0; i < iter; i++) {
			__c = ror8(candiates, i);
			if ((__c & 0xef) == 0xef)
				return start_delaynum + i * step;
		}
		for (i = 0; i < iter; i++) {
			__c = ror8(candiates, i);
			if ((__c & 0xc7) == 0xc7)
				return start_delaynum + i * step;
		}
		for (i = 0; i < iter; i++) {
			__c = ror8(candiates, i);
			if ((__c & 0x83) == 0x83)
				return start_delaynum + i * step;
		}
		step = step >> 1;
	} while (step >= MIN_STEP);

	return -1;
}

static int dw_mci_rk3288_execute_tuning(struct dw_mci_slot *slot, u32 opcode,
					struct dw_mci_tuning_data *tuning_data)
{
	struct dw_mci *host = slot->host;
	int ret = -EIO;
	int degree;
	int delaynum = 0;
	bool need_adjust_delaynum;

	dw_mci_rk3288_set_tuning_type(host);
	degree = dw_mci_rk3288_get_best_degree(
				slot, opcode, tuning_data,
				&need_adjust_delaynum);
	if (degree < 0) {
		ret = -EIO;
		goto exit;
	}

	dw_mci_rk3288_set_degree(host, degree);
	
	if (!need_adjust_delaynum) {
		ret =  0;
		goto exit;
	}

	delaynum = dw_mci_rk3288_get_best_delaynum(
			slot, opcode, tuning_data);
	if (delaynum >= 0) {
		dw_mci_rk3288_set_delaynum(host, delaynum);
		ret = 0;
		goto exit;
	}
	
exit:
	if (!ret)
		dev_info(host->dev,
			 "Tuning successfully: degree %d, delaynum %d\n",
			 degree, delaynum);
	return ret;
}

static unsigned long rockchip_dwmmc_caps[] = {
	MMC_CAP_CMD23 | MMC_CAP_UHS_SDR12 | MMC_CAP_UHS_SDR25 |
	MMC_CAP_UHS_SDR50 | MMC_CAP_UHS_SDR104,
	MMC_CAP_CMD23 | MMC_CAP_UHS_SDR12 | MMC_CAP_UHS_SDR25 |
	MMC_CAP_UHS_SDR50 | MMC_CAP_UHS_SDR104,
	MMC_CAP_CMD23,
	MMC_CAP_CMD23,
};

static const struct dw_mci_drv_data rk2928_drv_data = {
	.caps			= rockchip_dwmmc_caps,
	.prepare_command        = dw_mci_rockchip_prepare_command,
};

static const struct dw_mci_drv_data rk3288_drv_data = {
	.caps			= rockchip_dwmmc_caps,
	.parse_dt		= dw_mci_rk3288_parse_dt,
	.prepare_command        = dw_mci_rockchip_prepare_command,
	.set_ios		= dw_mci_rk3288_set_ios,
	.setup_clock		= dw_mci_rk3288_setup_clock,
	.execute_tuning = dw_mci_rk3288_execute_tuning,
};

static const struct of_device_id dw_mci_rockchip_match[] = {
	{ .compatible = "rockchip,rk2928-dw-mshc",
		.data = &rk2928_drv_data },
	{ .compatible = "rockchip,rk3288-dw-mshc",
		.data = &rk3288_drv_data },
	{},
};
MODULE_DEVICE_TABLE(of, dw_mci_rockchip_match);

static int dw_mci_rockchip_probe(struct platform_device *pdev)
{
	const struct dw_mci_drv_data *drv_data;
	const struct of_device_id *match;

	match = of_match_node(dw_mci_rockchip_match, pdev->dev.of_node);
	drv_data = match->data;

	return dw_mci_pltfm_register(pdev, drv_data);
}

#ifdef CONFIG_PM_SLEEP
static int dw_mci_rockchip_suspend(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);
	int ret;

	ret = dw_mci_suspend(host);
	if (!ret)
		clk_disable_unprepare(host->ciu_clk);

	return ret;
}

static int dw_mci_rockchip_resume(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);
	int ret;

	ret = clk_prepare_enable(host->ciu_clk);
	if (ret) {
		dev_err(host->dev, "failed to enable ciu clock\n");
		return ret;
	}

	return dw_mci_resume(host);
}
#endif /* CONFIG_PM_SLEEP */

static SIMPLE_DEV_PM_OPS(dw_mci_rockchip_pmops,
			 dw_mci_rockchip_suspend,
			 dw_mci_rockchip_resume);

static struct platform_driver dw_mci_rockchip_pltfm_driver = {
	.probe		= dw_mci_rockchip_probe,
	.remove		= dw_mci_pltfm_remove,
	.driver		= {
		.name		= "dwmmc_rockchip",
		.of_match_table	= dw_mci_rockchip_match,
		.pm		= &dw_mci_rockchip_pmops,
	},
};

module_platform_driver(dw_mci_rockchip_pltfm_driver);

MODULE_AUTHOR("Addy Ke <addy.ke@rock-chips.com>");
MODULE_DESCRIPTION("Rockchip Specific DW-MSHC Driver Extension");
MODULE_ALIAS("platform:dwmmc-rockchip");
MODULE_LICENSE("GPL v2");
